//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.seabay.polarion.Project {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.polarion.com/ProjectWebService", ConfigurationName="Project.ProjectWebService")]
    public interface ProjectWebService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUsersRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getUsersResponse getUsers(net.seabay.polarion.Project.getUsersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUserRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getUserResponse getUser(net.seabay.polarion.Project.getUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getProjectResponse getProject(net.seabay.polarion.Project.getProjectRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message createUserRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.createUserResponse createUser(net.seabay.polarion.Project.createUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUserAvatarURLRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getUserAvatarURLResponse getUserAvatarURL(net.seabay.polarion.Project.getUserAvatarURLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectUsersRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getProjectUsersResponse getProjectUsers(net.seabay.polarion.Project.getProjectUsersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getRootProjectGroupRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getRootProjectGroupResponse getRootProjectGroup(net.seabay.polarion.Project.getRootProjectGroupRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectAtLocationRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getProjectAtLocationResponse getProjectAtLocation(net.seabay.polarion.Project.getProjectAtLocationRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectGroupAtLocationRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getProjectGroupAtLocationResponse getProjectGroupAtLocation(net.seabay.polarion.Project.getProjectGroupAtLocationRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectGroupRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getProjectGroupResponse getProjectGroup(net.seabay.polarion.Project.getProjectGroupRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getContainedProjectsRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getContainedProjectsResponse getContainedProjects(net.seabay.polarion.Project.getContainedProjectsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getDeepContainedProjectsRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getDeepContainedProjectsResponse getDeepContainedProjects(net.seabay.polarion.Project.getDeepContainedProjectsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getContainedGroupsRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getContainedGroupsResponse getContainedGroups(net.seabay.polarion.Project.getContainedGroupsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message updateUserRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.updateUserResponse updateUser(net.seabay.polarion.Project.updateUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectByURIRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getProjectByURIResponse getProjectByURI(net.seabay.polarion.Project.getProjectByURIRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUserByUriRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Project.getUserByUriResponse getUserByUri(net.seabay.polarion.Project.getUserByUriRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/ProjectWebService-types")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Text descriptionField;
        
        private bool disabledNotificationsField;
        
        private bool disabledNotificationsFieldSpecified;
        
        private string emailField;
        
        private string idField;
        
        private string nameField;
        
        private string[] voteURIsField;
        
        private string[] watcheURIsField;
        
        private string uriField;
        
        private bool unresolvableField;
        
        private bool unresolvableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Text description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool disabledNotifications {
            get {
                return this.disabledNotificationsField;
            }
            set {
                this.disabledNotificationsField = value;
                this.RaisePropertyChanged("disabledNotifications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disabledNotificationsSpecified {
            get {
                return this.disabledNotificationsFieldSpecified;
            }
            set {
                this.disabledNotificationsFieldSpecified = value;
                this.RaisePropertyChanged("disabledNotificationsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubterraURI", Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] voteURIs {
            get {
                return this.voteURIsField;
            }
            set {
                this.voteURIsField = value;
                this.RaisePropertyChanged("voteURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubterraURI", Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] watcheURIs {
            get {
                return this.watcheURIsField;
            }
            set {
                this.watcheURIsField = value;
                this.RaisePropertyChanged("watcheURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool unresolvable {
            get {
                return this.unresolvableField;
            }
            set {
                this.unresolvableField = value;
                this.RaisePropertyChanged("unresolvable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unresolvableSpecified {
            get {
                return this.unresolvableFieldSpecified;
            }
            set {
                this.unresolvableFieldSpecified = value;
                this.RaisePropertyChanged("unresolvableSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/types")]
    public partial class Text : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string contentField;
        
        private bool contentLossyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool contentLossy {
            get {
                return this.contentLossyField;
            }
            set {
                this.contentLossyField = value;
                this.RaisePropertyChanged("contentLossy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/ProjectWebService-types")]
    public partial class ProjectGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] groupURIsField;
        
        private string locationField;
        
        private string nameField;
        
        private string parentURIField;
        
        private string[] projectIDsField;
        
        private string uriField;
        
        private bool unresolvableField;
        
        private bool unresolvableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubterraURI", Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] groupURIs {
            get {
                return this.groupURIsField;
            }
            set {
                this.groupURIsField = value;
                this.RaisePropertyChanged("groupURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string parentURI {
            get {
                return this.parentURIField;
            }
            set {
                this.parentURIField = value;
                this.RaisePropertyChanged("parentURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] projectIDs {
            get {
                return this.projectIDsField;
            }
            set {
                this.projectIDsField = value;
                this.RaisePropertyChanged("projectIDs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool unresolvable {
            get {
                return this.unresolvableField;
            }
            set {
                this.unresolvableField = value;
                this.RaisePropertyChanged("unresolvable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unresolvableSpecified {
            get {
                return this.unresolvableFieldSpecified;
            }
            set {
                this.unresolvableFieldSpecified = value;
                this.RaisePropertyChanged("unresolvableSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/ProjectWebService-types")]
    public partial class Project : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private Text descriptionField;
        
        private System.DateTime finishField;
        
        private bool finishFieldSpecified;
        
        private string idField;
        
        private User leadField;
        
        private string locationField;
        
        private System.DateTime lockWorkRecordsDateField;
        
        private bool lockWorkRecordsDateFieldSpecified;
        
        private string nameField;
        
        private string projectGroupURIField;
        
        private System.DateTime startField;
        
        private bool startFieldSpecified;
        
        private string trackerPrefixField;
        
        private string uriField;
        
        private bool unresolvableField;
        
        private bool unresolvableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Text description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime finish {
            get {
                return this.finishField;
            }
            set {
                this.finishField = value;
                this.RaisePropertyChanged("finish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finishSpecified {
            get {
                return this.finishFieldSpecified;
            }
            set {
                this.finishFieldSpecified = value;
                this.RaisePropertyChanged("finishSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public User lead {
            get {
                return this.leadField;
            }
            set {
                this.leadField = value;
                this.RaisePropertyChanged("lead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime lockWorkRecordsDate {
            get {
                return this.lockWorkRecordsDateField;
            }
            set {
                this.lockWorkRecordsDateField = value;
                this.RaisePropertyChanged("lockWorkRecordsDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lockWorkRecordsDateSpecified {
            get {
                return this.lockWorkRecordsDateFieldSpecified;
            }
            set {
                this.lockWorkRecordsDateFieldSpecified = value;
                this.RaisePropertyChanged("lockWorkRecordsDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string projectGroupURI {
            get {
                return this.projectGroupURIField;
            }
            set {
                this.projectGroupURIField = value;
                this.RaisePropertyChanged("projectGroupURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string trackerPrefix {
            get {
                return this.trackerPrefixField;
            }
            set {
                this.trackerPrefixField = value;
                this.RaisePropertyChanged("trackerPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool unresolvable {
            get {
                return this.unresolvableField;
            }
            set {
                this.unresolvableField = value;
                this.RaisePropertyChanged("unresolvable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unresolvableSpecified {
            get {
                return this.unresolvableFieldSpecified;
            }
            set {
                this.unresolvableFieldSpecified = value;
                this.RaisePropertyChanged("unresolvableSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsers", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUsersRequest {
        
        public getUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getUsersReturn")]
        public net.seabay.polarion.Project.User[] getUsersReturn;
        
        public getUsersResponse() {
        }
        
        public getUsersResponse(net.seabay.polarion.Project.User[] getUsersReturn) {
            this.getUsersReturn = getUsersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string userID;
        
        public getUserRequest() {
        }
        
        public getUserRequest(string userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.User getUserReturn;
        
        public getUserResponse() {
        }
        
        public getUserResponse(net.seabay.polarion.Project.User getUserReturn) {
            this.getUserReturn = getUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProject", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectID;
        
        public getProjectRequest() {
        }
        
        public getProjectRequest(string projectID) {
            this.projectID = projectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.Project getProjectReturn;
        
        public getProjectResponse() {
        }
        
        public getProjectResponse(net.seabay.polarion.Project.Project getProjectReturn) {
            this.getProjectReturn = getProjectReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUser", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class createUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string in0;
        
        public createUserRequest() {
        }
        
        public createUserRequest(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUserResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.User createUserReturn;
        
        public createUserResponse() {
        }
        
        public createUserResponse(net.seabay.polarion.Project.User createUserReturn) {
            this.createUserReturn = createUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserAvatarURL", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUserAvatarURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string userURI;
        
        public getUserAvatarURLRequest() {
        }
        
        public getUserAvatarURLRequest(string userURI) {
            this.userURI = userURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserAvatarURLResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUserAvatarURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string getUserAvatarURLReturn;
        
        public getUserAvatarURLResponse() {
        }
        
        public getUserAvatarURLResponse(string getUserAvatarURLReturn) {
            this.getUserAvatarURLReturn = getUserAvatarURLReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectUsers", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectID;
        
        public getProjectUsersRequest() {
        }
        
        public getProjectUsersRequest(string projectID) {
            this.projectID = projectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectUsersResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getProjectUsersReturn")]
        public net.seabay.polarion.Project.User[] getProjectUsersReturn;
        
        public getProjectUsersResponse() {
        }
        
        public getProjectUsersResponse(net.seabay.polarion.Project.User[] getProjectUsersReturn) {
            this.getProjectUsersReturn = getProjectUsersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRootProjectGroup", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getRootProjectGroupRequest {
        
        public getRootProjectGroupRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRootProjectGroupResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getRootProjectGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.ProjectGroup getRootProjectGroupReturn;
        
        public getRootProjectGroupResponse() {
        }
        
        public getRootProjectGroupResponse(net.seabay.polarion.Project.ProjectGroup getRootProjectGroupReturn) {
            this.getRootProjectGroupReturn = getRootProjectGroupReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectAtLocation", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectAtLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string location;
        
        public getProjectAtLocationRequest() {
        }
        
        public getProjectAtLocationRequest(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectAtLocationResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectAtLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.Project getProjectAtLocationReturn;
        
        public getProjectAtLocationResponse() {
        }
        
        public getProjectAtLocationResponse(net.seabay.polarion.Project.Project getProjectAtLocationReturn) {
            this.getProjectAtLocationReturn = getProjectAtLocationReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroupAtLocation", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectGroupAtLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string location;
        
        public getProjectGroupAtLocationRequest() {
        }
        
        public getProjectGroupAtLocationRequest(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroupAtLocationResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectGroupAtLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.ProjectGroup getProjectGroupAtLocationReturn;
        
        public getProjectGroupAtLocationResponse() {
        }
        
        public getProjectGroupAtLocationResponse(net.seabay.polarion.Project.ProjectGroup getProjectGroupAtLocationReturn) {
            this.getProjectGroupAtLocationReturn = getProjectGroupAtLocationReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroup", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getProjectGroupRequest() {
        }
        
        public getProjectGroupRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroupResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.ProjectGroup getProjectGroupReturn;
        
        public getProjectGroupResponse() {
        }
        
        public getProjectGroupResponse(net.seabay.polarion.Project.ProjectGroup getProjectGroupReturn) {
            this.getProjectGroupReturn = getProjectGroupReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedProjects", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getContainedProjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getContainedProjectsRequest() {
        }
        
        public getContainedProjectsRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedProjectsResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getContainedProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getContainedProjectsReturn")]
        public net.seabay.polarion.Project.Project[] getContainedProjectsReturn;
        
        public getContainedProjectsResponse() {
        }
        
        public getContainedProjectsResponse(net.seabay.polarion.Project.Project[] getContainedProjectsReturn) {
            this.getContainedProjectsReturn = getContainedProjectsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeepContainedProjects", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getDeepContainedProjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getDeepContainedProjectsRequest() {
        }
        
        public getDeepContainedProjectsRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeepContainedProjectsResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getDeepContainedProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getDeepContainedProjectsReturn")]
        public net.seabay.polarion.Project.Project[] getDeepContainedProjectsReturn;
        
        public getDeepContainedProjectsResponse() {
        }
        
        public getDeepContainedProjectsResponse(net.seabay.polarion.Project.Project[] getDeepContainedProjectsReturn) {
            this.getDeepContainedProjectsReturn = getDeepContainedProjectsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedGroups", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getContainedGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getContainedGroupsRequest() {
        }
        
        public getContainedGroupsRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedGroupsResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getContainedGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getContainedGroupsReturn")]
        public net.seabay.polarion.Project.ProjectGroup[] getContainedGroupsReturn;
        
        public getContainedGroupsResponse() {
        }
        
        public getContainedGroupsResponse(net.seabay.polarion.Project.ProjectGroup[] getContainedGroupsReturn) {
            this.getContainedGroupsReturn = getContainedGroupsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUser", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class updateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.User in0;
        
        public updateUserRequest() {
        }
        
        public updateUserRequest(net.seabay.polarion.Project.User in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUserResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class updateUserResponse {
        
        public updateUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectByURI", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectByURIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectURI;
        
        public getProjectByURIRequest() {
        }
        
        public getProjectByURIRequest(string projectURI) {
            this.projectURI = projectURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectByURIResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getProjectByURIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.Project getProjectByURIReturn;
        
        public getProjectByURIResponse() {
        }
        
        public getProjectByURIResponse(net.seabay.polarion.Project.Project getProjectByURIReturn) {
            this.getProjectByURIReturn = getProjectByURIReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByUri", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUserByUriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string userURI;
        
        public getUserByUriRequest() {
        }
        
        public getUserByUriRequest(string userURI) {
            this.userURI = userURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByUriResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    public partial class getUserByUriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public net.seabay.polarion.Project.User getUserByUriReturn;
        
        public getUserByUriResponse() {
        }
        
        public getUserByUriResponse(net.seabay.polarion.Project.User getUserByUriReturn) {
            this.getUserByUriReturn = getUserByUriReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjectWebServiceChannel : net.seabay.polarion.Project.ProjectWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectWebServiceClient : System.ServiceModel.ClientBase<net.seabay.polarion.Project.ProjectWebService>, net.seabay.polarion.Project.ProjectWebService {
        
        public ProjectWebServiceClient() {
        }
        
        public ProjectWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getUsersResponse net.seabay.polarion.Project.ProjectWebService.getUsers(net.seabay.polarion.Project.getUsersRequest request) {
            return base.Channel.getUsers(request);
        }
        
        public net.seabay.polarion.Project.User[] getUsers() {
            net.seabay.polarion.Project.getUsersRequest inValue = new net.seabay.polarion.Project.getUsersRequest();
            net.seabay.polarion.Project.getUsersResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getUsers(inValue);
            return retVal.getUsersReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getUserResponse net.seabay.polarion.Project.ProjectWebService.getUser(net.seabay.polarion.Project.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public net.seabay.polarion.Project.User getUser(string userID) {
            net.seabay.polarion.Project.getUserRequest inValue = new net.seabay.polarion.Project.getUserRequest();
            inValue.userID = userID;
            net.seabay.polarion.Project.getUserResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getUser(inValue);
            return retVal.getUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getProjectResponse net.seabay.polarion.Project.ProjectWebService.getProject(net.seabay.polarion.Project.getProjectRequest request) {
            return base.Channel.getProject(request);
        }
        
        public net.seabay.polarion.Project.Project getProject(string projectID) {
            net.seabay.polarion.Project.getProjectRequest inValue = new net.seabay.polarion.Project.getProjectRequest();
            inValue.projectID = projectID;
            net.seabay.polarion.Project.getProjectResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getProject(inValue);
            return retVal.getProjectReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.createUserResponse net.seabay.polarion.Project.ProjectWebService.createUser(net.seabay.polarion.Project.createUserRequest request) {
            return base.Channel.createUser(request);
        }
        
        public net.seabay.polarion.Project.User createUser(string in0) {
            net.seabay.polarion.Project.createUserRequest inValue = new net.seabay.polarion.Project.createUserRequest();
            inValue.in0 = in0;
            net.seabay.polarion.Project.createUserResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).createUser(inValue);
            return retVal.createUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getUserAvatarURLResponse net.seabay.polarion.Project.ProjectWebService.getUserAvatarURL(net.seabay.polarion.Project.getUserAvatarURLRequest request) {
            return base.Channel.getUserAvatarURL(request);
        }
        
        public string getUserAvatarURL(string userURI) {
            net.seabay.polarion.Project.getUserAvatarURLRequest inValue = new net.seabay.polarion.Project.getUserAvatarURLRequest();
            inValue.userURI = userURI;
            net.seabay.polarion.Project.getUserAvatarURLResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getUserAvatarURL(inValue);
            return retVal.getUserAvatarURLReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getProjectUsersResponse net.seabay.polarion.Project.ProjectWebService.getProjectUsers(net.seabay.polarion.Project.getProjectUsersRequest request) {
            return base.Channel.getProjectUsers(request);
        }
        
        public net.seabay.polarion.Project.User[] getProjectUsers(string projectID) {
            net.seabay.polarion.Project.getProjectUsersRequest inValue = new net.seabay.polarion.Project.getProjectUsersRequest();
            inValue.projectID = projectID;
            net.seabay.polarion.Project.getProjectUsersResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getProjectUsers(inValue);
            return retVal.getProjectUsersReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getRootProjectGroupResponse net.seabay.polarion.Project.ProjectWebService.getRootProjectGroup(net.seabay.polarion.Project.getRootProjectGroupRequest request) {
            return base.Channel.getRootProjectGroup(request);
        }
        
        public net.seabay.polarion.Project.ProjectGroup getRootProjectGroup() {
            net.seabay.polarion.Project.getRootProjectGroupRequest inValue = new net.seabay.polarion.Project.getRootProjectGroupRequest();
            net.seabay.polarion.Project.getRootProjectGroupResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getRootProjectGroup(inValue);
            return retVal.getRootProjectGroupReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getProjectAtLocationResponse net.seabay.polarion.Project.ProjectWebService.getProjectAtLocation(net.seabay.polarion.Project.getProjectAtLocationRequest request) {
            return base.Channel.getProjectAtLocation(request);
        }
        
        public net.seabay.polarion.Project.Project getProjectAtLocation(string location) {
            net.seabay.polarion.Project.getProjectAtLocationRequest inValue = new net.seabay.polarion.Project.getProjectAtLocationRequest();
            inValue.location = location;
            net.seabay.polarion.Project.getProjectAtLocationResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getProjectAtLocation(inValue);
            return retVal.getProjectAtLocationReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getProjectGroupAtLocationResponse net.seabay.polarion.Project.ProjectWebService.getProjectGroupAtLocation(net.seabay.polarion.Project.getProjectGroupAtLocationRequest request) {
            return base.Channel.getProjectGroupAtLocation(request);
        }
        
        public net.seabay.polarion.Project.ProjectGroup getProjectGroupAtLocation(string location) {
            net.seabay.polarion.Project.getProjectGroupAtLocationRequest inValue = new net.seabay.polarion.Project.getProjectGroupAtLocationRequest();
            inValue.location = location;
            net.seabay.polarion.Project.getProjectGroupAtLocationResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getProjectGroupAtLocation(inValue);
            return retVal.getProjectGroupAtLocationReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getProjectGroupResponse net.seabay.polarion.Project.ProjectWebService.getProjectGroup(net.seabay.polarion.Project.getProjectGroupRequest request) {
            return base.Channel.getProjectGroup(request);
        }
        
        public net.seabay.polarion.Project.ProjectGroup getProjectGroup(string projectGroupURI) {
            net.seabay.polarion.Project.getProjectGroupRequest inValue = new net.seabay.polarion.Project.getProjectGroupRequest();
            inValue.projectGroupURI = projectGroupURI;
            net.seabay.polarion.Project.getProjectGroupResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getProjectGroup(inValue);
            return retVal.getProjectGroupReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getContainedProjectsResponse net.seabay.polarion.Project.ProjectWebService.getContainedProjects(net.seabay.polarion.Project.getContainedProjectsRequest request) {
            return base.Channel.getContainedProjects(request);
        }
        
        public net.seabay.polarion.Project.Project[] getContainedProjects(string projectGroupURI) {
            net.seabay.polarion.Project.getContainedProjectsRequest inValue = new net.seabay.polarion.Project.getContainedProjectsRequest();
            inValue.projectGroupURI = projectGroupURI;
            net.seabay.polarion.Project.getContainedProjectsResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getContainedProjects(inValue);
            return retVal.getContainedProjectsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getDeepContainedProjectsResponse net.seabay.polarion.Project.ProjectWebService.getDeepContainedProjects(net.seabay.polarion.Project.getDeepContainedProjectsRequest request) {
            return base.Channel.getDeepContainedProjects(request);
        }
        
        public net.seabay.polarion.Project.Project[] getDeepContainedProjects(string projectGroupURI) {
            net.seabay.polarion.Project.getDeepContainedProjectsRequest inValue = new net.seabay.polarion.Project.getDeepContainedProjectsRequest();
            inValue.projectGroupURI = projectGroupURI;
            net.seabay.polarion.Project.getDeepContainedProjectsResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getDeepContainedProjects(inValue);
            return retVal.getDeepContainedProjectsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getContainedGroupsResponse net.seabay.polarion.Project.ProjectWebService.getContainedGroups(net.seabay.polarion.Project.getContainedGroupsRequest request) {
            return base.Channel.getContainedGroups(request);
        }
        
        public net.seabay.polarion.Project.ProjectGroup[] getContainedGroups(string projectGroupURI) {
            net.seabay.polarion.Project.getContainedGroupsRequest inValue = new net.seabay.polarion.Project.getContainedGroupsRequest();
            inValue.projectGroupURI = projectGroupURI;
            net.seabay.polarion.Project.getContainedGroupsResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getContainedGroups(inValue);
            return retVal.getContainedGroupsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.updateUserResponse net.seabay.polarion.Project.ProjectWebService.updateUser(net.seabay.polarion.Project.updateUserRequest request) {
            return base.Channel.updateUser(request);
        }
        
        public void updateUser(net.seabay.polarion.Project.User in0) {
            net.seabay.polarion.Project.updateUserRequest inValue = new net.seabay.polarion.Project.updateUserRequest();
            inValue.in0 = in0;
            net.seabay.polarion.Project.updateUserResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).updateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getProjectByURIResponse net.seabay.polarion.Project.ProjectWebService.getProjectByURI(net.seabay.polarion.Project.getProjectByURIRequest request) {
            return base.Channel.getProjectByURI(request);
        }
        
        public net.seabay.polarion.Project.Project getProjectByURI(string projectURI) {
            net.seabay.polarion.Project.getProjectByURIRequest inValue = new net.seabay.polarion.Project.getProjectByURIRequest();
            inValue.projectURI = projectURI;
            net.seabay.polarion.Project.getProjectByURIResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getProjectByURI(inValue);
            return retVal.getProjectByURIReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Project.getUserByUriResponse net.seabay.polarion.Project.ProjectWebService.getUserByUri(net.seabay.polarion.Project.getUserByUriRequest request) {
            return base.Channel.getUserByUri(request);
        }
        
        public net.seabay.polarion.Project.User getUserByUri(string userURI) {
            net.seabay.polarion.Project.getUserByUriRequest inValue = new net.seabay.polarion.Project.getUserByUriRequest();
            inValue.userURI = userURI;
            net.seabay.polarion.Project.getUserByUriResponse retVal = ((net.seabay.polarion.Project.ProjectWebService)(this)).getUserByUri(inValue);
            return retVal.getUserByUriReturn;
        }
    }
}
