//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.seabay.polarion.Session {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.polarion.com/SessionWebService", ConfigurationName="Session.SessionWebService")]
    public interface SessionWebService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SessionWebService-impl) of message LogInRequest does not match the default value (http://ws.polarion.com/SessionWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        net.seabay.polarion.Session.LogInResponse LogIn(net.seabay.polarion.Session.LogInRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SessionWebService-impl) of message endSessionRequest does not match the default value (http://ws.polarion.com/SessionWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        net.seabay.polarion.Session.endSessionResponse endSession(net.seabay.polarion.Session.endSessionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SessionWebService-impl) of message hasSubjectRequest does not match the default value (http://ws.polarion.com/SessionWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        net.seabay.polarion.Session.hasSubjectResponse hasSubject(net.seabay.polarion.Session.hasSubjectRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SessionWebService-impl) of message beginTransactionRequest does not match the default value (http://ws.polarion.com/SessionWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        net.seabay.polarion.Session.beginTransactionResponse beginTransaction(net.seabay.polarion.Session.beginTransactionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SessionWebService-impl) of message endTransactionRequest does not match the default value (http://ws.polarion.com/SessionWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        net.seabay.polarion.Session.endTransactionResponse endTransaction(net.seabay.polarion.Session.endTransactionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SessionWebService-impl) of message transactionExistsRequest does not match the default value (http://ws.polarion.com/SessionWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        net.seabay.polarion.Session.transactionExistsResponse transactionExists(net.seabay.polarion.Session.transactionExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogIn", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=1)]
        public string password;
        
        public LogInRequest() {
        }
        
        public LogInRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogInResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class LogInResponse {
        
        public LogInResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endSession", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endSessionRequest {
        
        public endSessionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endSessionResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endSessionResponse {
        
        public endSessionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasSubject", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class hasSubjectRequest {
        
        public hasSubjectRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasSubjectResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class hasSubjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public bool hasSubjectReturn;
        
        public hasSubjectResponse() {
        }
        
        public hasSubjectResponse(bool hasSubjectReturn) {
            this.hasSubjectReturn = hasSubjectReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="beginTransaction", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class beginTransactionRequest {
        
        public beginTransactionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="beginTransactionResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class beginTransactionResponse {
        
        public beginTransactionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endTransaction", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public bool rollback;
        
        public endTransactionRequest() {
        }
        
        public endTransactionRequest(bool rollback) {
            this.rollback = rollback;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endTransactionResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endTransactionResponse {
        
        public endTransactionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionExists", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class transactionExistsRequest {
        
        public transactionExistsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionExistsResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class transactionExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public bool transactionExistsReturn;
        
        public transactionExistsResponse() {
        }
        
        public transactionExistsResponse(bool transactionExistsReturn) {
            this.transactionExistsReturn = transactionExistsReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionWebServiceChannel : net.seabay.polarion.Session.SessionWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionWebServiceClient : System.ServiceModel.ClientBase<net.seabay.polarion.Session.SessionWebService>, net.seabay.polarion.Session.SessionWebService {
        
        public SessionWebServiceClient() {
        }
        
        public SessionWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Session.LogInResponse net.seabay.polarion.Session.SessionWebService.LogIn(net.seabay.polarion.Session.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public void LogIn(string userName, string password) {
            net.seabay.polarion.Session.LogInRequest inValue = new net.seabay.polarion.Session.LogInRequest();
            inValue.userName = userName;
            inValue.password = password;
            net.seabay.polarion.Session.LogInResponse retVal = ((net.seabay.polarion.Session.SessionWebService)(this)).LogIn(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Session.endSessionResponse net.seabay.polarion.Session.SessionWebService.endSession(net.seabay.polarion.Session.endSessionRequest request) {
            return base.Channel.endSession(request);
        }
        
        public void endSession() {
            net.seabay.polarion.Session.endSessionRequest inValue = new net.seabay.polarion.Session.endSessionRequest();
            net.seabay.polarion.Session.endSessionResponse retVal = ((net.seabay.polarion.Session.SessionWebService)(this)).endSession(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Session.hasSubjectResponse net.seabay.polarion.Session.SessionWebService.hasSubject(net.seabay.polarion.Session.hasSubjectRequest request) {
            return base.Channel.hasSubject(request);
        }
        
        public bool hasSubject() {
            net.seabay.polarion.Session.hasSubjectRequest inValue = new net.seabay.polarion.Session.hasSubjectRequest();
            net.seabay.polarion.Session.hasSubjectResponse retVal = ((net.seabay.polarion.Session.SessionWebService)(this)).hasSubject(inValue);
            return retVal.hasSubjectReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Session.beginTransactionResponse net.seabay.polarion.Session.SessionWebService.beginTransaction(net.seabay.polarion.Session.beginTransactionRequest request) {
            return base.Channel.beginTransaction(request);
        }
        
        public void beginTransaction() {
            net.seabay.polarion.Session.beginTransactionRequest inValue = new net.seabay.polarion.Session.beginTransactionRequest();
            net.seabay.polarion.Session.beginTransactionResponse retVal = ((net.seabay.polarion.Session.SessionWebService)(this)).beginTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Session.endTransactionResponse net.seabay.polarion.Session.SessionWebService.endTransaction(net.seabay.polarion.Session.endTransactionRequest request) {
            return base.Channel.endTransaction(request);
        }
        
        public void endTransaction(bool rollback) {
            net.seabay.polarion.Session.endTransactionRequest inValue = new net.seabay.polarion.Session.endTransactionRequest();
            inValue.rollback = rollback;
            net.seabay.polarion.Session.endTransactionResponse retVal = ((net.seabay.polarion.Session.SessionWebService)(this)).endTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Session.transactionExistsResponse net.seabay.polarion.Session.SessionWebService.transactionExists(net.seabay.polarion.Session.transactionExistsRequest request) {
            return base.Channel.transactionExists(request);
        }
        
        public bool transactionExists() {
            net.seabay.polarion.Session.transactionExistsRequest inValue = new net.seabay.polarion.Session.transactionExistsRequest();
            net.seabay.polarion.Session.transactionExistsResponse retVal = ((net.seabay.polarion.Session.SessionWebService)(this)).transactionExists(inValue);
            return retVal.transactionExistsReturn;
        }
    }
}
