//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.seabay.polarion.Connector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.seabay.polarion.Connector.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /polarion/ws/services/.
        /// </summary>
        internal static string BASEWSURL {
            get {
                return ResourceManager.GetString("BASEWSURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuilderWebService.
        /// </summary>
        internal static string BUILDERURL {
            get {
                return ResourceManager.GetString("BUILDERURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectWebService.
        /// </summary>
        internal static string PROJECTURL {
            get {
                return ResourceManager.GetString("PROJECTURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https:.
        /// </summary>
        internal static string SECUREPROTOCOL {
            get {
                return ResourceManager.GetString("SECUREPROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityWebService.
        /// </summary>
        internal static string SECURITYURL {
            get {
                return ResourceManager.GetString("SECURITYURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionWebService.
        /// </summary>
        internal static string SESSIONURL {
            get {
                return ResourceManager.GetString("SESSIONURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAvailableManagementWebService.
        /// </summary>
        internal static string TESTMANAGEMENTURL {
            get {
                return ResourceManager.GetString("TESTMANAGEMENTURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackerWebService.
        /// </summary>
        internal static string TRACKERURL {
            get {
                return ResourceManager.GetString("TRACKERURL", resourceCulture);
            }
        }
    }
}
