//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.seabay.polarion.Security {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.polarion.com/SecurityWebService", ConfigurationName="Security.SecurityWebService")]
    public interface SecurityWebService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message hasPermissionRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.hasPermissionResponse hasPermission(net.seabay.polarion.Security.hasPermissionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message getProductLicenseRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.getProductLicenseResponse getProductLicense(net.seabay.polarion.Security.getProductLicenseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message getGlobalRolesRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.getGlobalRolesResponse getGlobalRoles(net.seabay.polarion.Security.getGlobalRolesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message getContextRolesRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.getContextRolesResponse getContextRoles(net.seabay.polarion.Security.getContextRolesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message getRolesForUserRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.getRolesForUserResponse getRolesForUser(net.seabay.polarion.Security.getRolesForUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message getContextRolesForUserRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.getContextRolesForUserResponse getContextRolesForUser(net.seabay.polarion.Security.getContextRolesForUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canCreateInstancesRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canCreateInstancesResponse canCreateInstances(net.seabay.polarion.Security.canCreateInstancesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canReadInstanceRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canReadInstanceResponse canReadInstance(net.seabay.polarion.Security.canReadInstanceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canModifyInstanceRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canModifyInstanceResponse canModifyInstance(net.seabay.polarion.Security.canModifyInstanceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canDeleteInstanceRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canDeleteInstanceResponse canDeleteInstance(net.seabay.polarion.Security.canDeleteInstanceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canReadKeyRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canReadKeyResponse canReadKey(net.seabay.polarion.Security.canReadKeyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canModifyKeyRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canModifyKeyResponse canModifyKey(net.seabay.polarion.Security.canModifyKeyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canAddElementToKeyRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canAddElementToKeyResponse canAddElementToKey(net.seabay.polarion.Security.canAddElementToKeyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message canRemoveElementFromKeyRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.canRemoveElementFromKeyResponse canRemoveElementFromKey(net.seabay.polarion.Security.canRemoveElementFromKeyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message getLocationForURIRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.getLocationForURIResponse getLocationForURI(net.seabay.polarion.Security.getLocationForURIRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/SecurityWebService-impl) of message hasCurrentUserPermissionRequest does not match the default value (http://ws.polarion.com/SecurityWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.seabay.polarion.Security.hasCurrentUserPermissionResponse hasCurrentUserPermission(net.seabay.polarion.Security.hasCurrentUserPermissionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasPermission", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class hasPermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string permission;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=2)]
        public string projectId;
        
        public hasPermissionRequest() {
        }
        
        public hasPermissionRequest(string userId, string permission, string projectId) {
            this.userId = userId;
            this.permission = permission;
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasPermissionResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class hasPermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool hasPermissionReturn;
        
        public hasPermissionResponse() {
        }
        
        public hasPermissionResponse(bool hasPermissionReturn) {
            this.hasPermissionReturn = hasPermissionReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/SecurityWebService-types")]
    public partial class ProductLicense : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LicenseInfo[] concurrentLicenseDataField;
        
        private string customerCompanyField;
        
        private string customerEmailField;
        
        private string customerNameField;
        
        private System.Nullable<System.DateTime> dateCreatedField;
        
        private System.Nullable<System.DateTime> expirationDateField;
        
        private string generatedByField;
        
        private string ipAddressField;
        
        private string licenseFormatField;
        
        private string licenseProfileField;
        
        private string macAddressField;
        
        private LicenseInfo[] namedLicenseDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://ws.polarion.com/SecurityWebService", IsNullable=false)]
        public LicenseInfo[] concurrentLicenseData {
            get {
                return this.concurrentLicenseDataField;
            }
            set {
                this.concurrentLicenseDataField = value;
                this.RaisePropertyChanged("concurrentLicenseData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string customerCompany {
            get {
                return this.customerCompanyField;
            }
            set {
                this.customerCompanyField = value;
                this.RaisePropertyChanged("customerCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string customerEmail {
            get {
                return this.customerEmailField;
            }
            set {
                this.customerEmailField = value;
                this.RaisePropertyChanged("customerEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("customerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("dateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("expirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string generatedBy {
            get {
                return this.generatedByField;
            }
            set {
                this.generatedByField = value;
                this.RaisePropertyChanged("generatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("ipAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string licenseFormat {
            get {
                return this.licenseFormatField;
            }
            set {
                this.licenseFormatField = value;
                this.RaisePropertyChanged("licenseFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string licenseProfile {
            get {
                return this.licenseProfileField;
            }
            set {
                this.licenseProfileField = value;
                this.RaisePropertyChanged("licenseProfile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string macAddress {
            get {
                return this.macAddressField;
            }
            set {
                this.macAddressField = value;
                this.RaisePropertyChanged("macAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://ws.polarion.com/SecurityWebService", IsNullable=false)]
        public LicenseInfo[] namedLicenseData {
            get {
                return this.namedLicenseDataField;
            }
            set {
                this.namedLicenseDataField = value;
                this.RaisePropertyChanged("namedLicenseData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/SecurityWebService-types")]
    public partial class LicenseInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string licenseField;
        
        private int slotsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string license {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
                this.RaisePropertyChanged("license");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int slots {
            get {
                return this.slotsField;
            }
            set {
                this.slotsField = value;
                this.RaisePropertyChanged("slots");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductLicense", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getProductLicenseRequest {
        
        public getProductLicenseRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductLicenseResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getProductLicenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public net.seabay.polarion.Security.ProductLicense getProductLicenseReturn;
        
        public getProductLicenseResponse() {
        }
        
        public getProductLicenseResponse(net.seabay.polarion.Security.ProductLicense getProductLicenseReturn) {
            this.getProductLicenseReturn = getProductLicenseReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGlobalRoles", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getGlobalRolesRequest {
        
        public getGlobalRolesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGlobalRolesResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getGlobalRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getGlobalRolesReturn")]
        public string[] getGlobalRolesReturn;
        
        public getGlobalRolesResponse() {
        }
        
        public getGlobalRolesResponse(string[] getGlobalRolesReturn) {
            this.getGlobalRolesReturn = getGlobalRolesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContextRoles", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getContextRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string location;
        
        public getContextRolesRequest() {
        }
        
        public getContextRolesRequest(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContextRolesResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getContextRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getContextRolesReturn")]
        public string[] getContextRolesReturn;
        
        public getContextRolesResponse() {
        }
        
        public getContextRolesResponse(string[] getContextRolesReturn) {
            this.getContextRolesReturn = getContextRolesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRolesForUser", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getRolesForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string location;
        
        public getRolesForUserRequest() {
        }
        
        public getRolesForUserRequest(string userId, string location) {
            this.userId = userId;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRolesForUserResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getRolesForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getRolesForUserReturn")]
        public string[] getRolesForUserReturn;
        
        public getRolesForUserResponse() {
        }
        
        public getRolesForUserResponse(string[] getRolesForUserReturn) {
            this.getRolesForUserReturn = getRolesForUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContextRolesForUser", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getContextRolesForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string location;
        
        public getContextRolesForUserRequest() {
        }
        
        public getContextRolesForUserRequest(string userId, string location) {
            this.userId = userId;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContextRolesForUserResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getContextRolesForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getContextRolesForUserReturn")]
        public string[] getContextRolesForUserReturn;
        
        public getContextRolesForUserResponse() {
        }
        
        public getContextRolesForUserResponse(string[] getContextRolesForUserReturn) {
            this.getContextRolesForUserReturn = getContextRolesForUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canCreateInstances", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canCreateInstancesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string prototype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string projectId;
        
        public canCreateInstancesRequest() {
        }
        
        public canCreateInstancesRequest(string prototype, string projectId) {
            this.prototype = prototype;
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canCreateInstancesResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canCreateInstancesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canCreateInstancesReturn;
        
        public canCreateInstancesResponse() {
        }
        
        public canCreateInstancesResponse(bool canCreateInstancesReturn) {
            this.canCreateInstancesReturn = canCreateInstancesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canReadInstance", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canReadInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        public canReadInstanceRequest() {
        }
        
        public canReadInstanceRequest(string uri) {
            this.uri = uri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canReadInstanceResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canReadInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canReadInstanceReturn;
        
        public canReadInstanceResponse() {
        }
        
        public canReadInstanceResponse(bool canReadInstanceReturn) {
            this.canReadInstanceReturn = canReadInstanceReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canModifyInstance", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canModifyInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        public canModifyInstanceRequest() {
        }
        
        public canModifyInstanceRequest(string uri) {
            this.uri = uri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canModifyInstanceResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canModifyInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canModifyInstanceReturn;
        
        public canModifyInstanceResponse() {
        }
        
        public canModifyInstanceResponse(bool canModifyInstanceReturn) {
            this.canModifyInstanceReturn = canModifyInstanceReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canDeleteInstance", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canDeleteInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        public canDeleteInstanceRequest() {
        }
        
        public canDeleteInstanceRequest(string uri) {
            this.uri = uri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canDeleteInstanceResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canDeleteInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canDeleteInstanceReturn;
        
        public canDeleteInstanceResponse() {
        }
        
        public canDeleteInstanceResponse(bool canDeleteInstanceReturn) {
            this.canDeleteInstanceReturn = canDeleteInstanceReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canReadKey", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canReadKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string key;
        
        public canReadKeyRequest() {
        }
        
        public canReadKeyRequest(string uri, string key) {
            this.uri = uri;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canReadKeyResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canReadKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canReadKeyReturn;
        
        public canReadKeyResponse() {
        }
        
        public canReadKeyResponse(bool canReadKeyReturn) {
            this.canReadKeyReturn = canReadKeyReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canModifyKey", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canModifyKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string key;
        
        public canModifyKeyRequest() {
        }
        
        public canModifyKeyRequest(string uri, string key) {
            this.uri = uri;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canModifyKeyResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canModifyKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canModifyKeyReturn;
        
        public canModifyKeyResponse() {
        }
        
        public canModifyKeyResponse(bool canModifyKeyReturn) {
            this.canModifyKeyReturn = canModifyKeyReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canAddElementToKey", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canAddElementToKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string key;
        
        public canAddElementToKeyRequest() {
        }
        
        public canAddElementToKeyRequest(string uri, string key) {
            this.uri = uri;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canAddElementToKeyResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canAddElementToKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canAddElementToKeyReturn;
        
        public canAddElementToKeyResponse() {
        }
        
        public canAddElementToKeyResponse(bool canAddElementToKeyReturn) {
            this.canAddElementToKeyReturn = canAddElementToKeyReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canRemoveElementFromKey", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canRemoveElementFromKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string key;
        
        public canRemoveElementFromKeyRequest() {
        }
        
        public canRemoveElementFromKeyRequest(string uri, string key) {
            this.uri = uri;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canRemoveElementFromKeyResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class canRemoveElementFromKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool canRemoveElementFromKeyReturn;
        
        public canRemoveElementFromKeyResponse() {
        }
        
        public canRemoveElementFromKeyResponse(bool canRemoveElementFromKeyReturn) {
            this.canRemoveElementFromKeyReturn = canRemoveElementFromKeyReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocationForURI", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getLocationForURIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string uri;
        
        public getLocationForURIRequest() {
        }
        
        public getLocationForURIRequest(string uri) {
            this.uri = uri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocationForURIResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class getLocationForURIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string getLocationForURIReturn;
        
        public getLocationForURIResponse() {
        }
        
        public getLocationForURIResponse(string getLocationForURIReturn) {
            this.getLocationForURIReturn = getLocationForURIReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasCurrentUserPermission", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class hasCurrentUserPermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public string permission;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=1)]
        public string projectId;
        
        public hasCurrentUserPermissionRequest() {
        }
        
        public hasCurrentUserPermissionRequest(string permission, string projectId) {
            this.permission = permission;
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasCurrentUserPermissionResponse", WrapperNamespace="http://ws.polarion.com/SecurityWebService-impl", IsWrapped=true)]
    public partial class hasCurrentUserPermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SecurityWebService-impl", Order=0)]
        public bool hasCurrentUserPermissionReturn;
        
        public hasCurrentUserPermissionResponse() {
        }
        
        public hasCurrentUserPermissionResponse(bool hasCurrentUserPermissionReturn) {
            this.hasCurrentUserPermissionReturn = hasCurrentUserPermissionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecurityWebServiceChannel : net.seabay.polarion.Security.SecurityWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityWebServiceClient : System.ServiceModel.ClientBase<net.seabay.polarion.Security.SecurityWebService>, net.seabay.polarion.Security.SecurityWebService {
        
        public SecurityWebServiceClient() {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.hasPermissionResponse net.seabay.polarion.Security.SecurityWebService.hasPermission(net.seabay.polarion.Security.hasPermissionRequest request) {
            return base.Channel.hasPermission(request);
        }
        
        public bool hasPermission(string userId, string permission, string projectId) {
            net.seabay.polarion.Security.hasPermissionRequest inValue = new net.seabay.polarion.Security.hasPermissionRequest();
            inValue.userId = userId;
            inValue.permission = permission;
            inValue.projectId = projectId;
            net.seabay.polarion.Security.hasPermissionResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).hasPermission(inValue);
            return retVal.hasPermissionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.getProductLicenseResponse net.seabay.polarion.Security.SecurityWebService.getProductLicense(net.seabay.polarion.Security.getProductLicenseRequest request) {
            return base.Channel.getProductLicense(request);
        }
        
        public net.seabay.polarion.Security.ProductLicense getProductLicense() {
            net.seabay.polarion.Security.getProductLicenseRequest inValue = new net.seabay.polarion.Security.getProductLicenseRequest();
            net.seabay.polarion.Security.getProductLicenseResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).getProductLicense(inValue);
            return retVal.getProductLicenseReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.getGlobalRolesResponse net.seabay.polarion.Security.SecurityWebService.getGlobalRoles(net.seabay.polarion.Security.getGlobalRolesRequest request) {
            return base.Channel.getGlobalRoles(request);
        }
        
        public string[] getGlobalRoles() {
            net.seabay.polarion.Security.getGlobalRolesRequest inValue = new net.seabay.polarion.Security.getGlobalRolesRequest();
            net.seabay.polarion.Security.getGlobalRolesResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).getGlobalRoles(inValue);
            return retVal.getGlobalRolesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.getContextRolesResponse net.seabay.polarion.Security.SecurityWebService.getContextRoles(net.seabay.polarion.Security.getContextRolesRequest request) {
            return base.Channel.getContextRoles(request);
        }
        
        public string[] getContextRoles(string location) {
            net.seabay.polarion.Security.getContextRolesRequest inValue = new net.seabay.polarion.Security.getContextRolesRequest();
            inValue.location = location;
            net.seabay.polarion.Security.getContextRolesResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).getContextRoles(inValue);
            return retVal.getContextRolesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.getRolesForUserResponse net.seabay.polarion.Security.SecurityWebService.getRolesForUser(net.seabay.polarion.Security.getRolesForUserRequest request) {
            return base.Channel.getRolesForUser(request);
        }
        
        public string[] getRolesForUser(string userId, string location) {
            net.seabay.polarion.Security.getRolesForUserRequest inValue = new net.seabay.polarion.Security.getRolesForUserRequest();
            inValue.userId = userId;
            inValue.location = location;
            net.seabay.polarion.Security.getRolesForUserResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).getRolesForUser(inValue);
            return retVal.getRolesForUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.getContextRolesForUserResponse net.seabay.polarion.Security.SecurityWebService.getContextRolesForUser(net.seabay.polarion.Security.getContextRolesForUserRequest request) {
            return base.Channel.getContextRolesForUser(request);
        }
        
        public string[] getContextRolesForUser(string userId, string location) {
            net.seabay.polarion.Security.getContextRolesForUserRequest inValue = new net.seabay.polarion.Security.getContextRolesForUserRequest();
            inValue.userId = userId;
            inValue.location = location;
            net.seabay.polarion.Security.getContextRolesForUserResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).getContextRolesForUser(inValue);
            return retVal.getContextRolesForUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canCreateInstancesResponse net.seabay.polarion.Security.SecurityWebService.canCreateInstances(net.seabay.polarion.Security.canCreateInstancesRequest request) {
            return base.Channel.canCreateInstances(request);
        }
        
        public bool canCreateInstances(string prototype, string projectId) {
            net.seabay.polarion.Security.canCreateInstancesRequest inValue = new net.seabay.polarion.Security.canCreateInstancesRequest();
            inValue.prototype = prototype;
            inValue.projectId = projectId;
            net.seabay.polarion.Security.canCreateInstancesResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canCreateInstances(inValue);
            return retVal.canCreateInstancesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canReadInstanceResponse net.seabay.polarion.Security.SecurityWebService.canReadInstance(net.seabay.polarion.Security.canReadInstanceRequest request) {
            return base.Channel.canReadInstance(request);
        }
        
        public bool canReadInstance(string uri) {
            net.seabay.polarion.Security.canReadInstanceRequest inValue = new net.seabay.polarion.Security.canReadInstanceRequest();
            inValue.uri = uri;
            net.seabay.polarion.Security.canReadInstanceResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canReadInstance(inValue);
            return retVal.canReadInstanceReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canModifyInstanceResponse net.seabay.polarion.Security.SecurityWebService.canModifyInstance(net.seabay.polarion.Security.canModifyInstanceRequest request) {
            return base.Channel.canModifyInstance(request);
        }
        
        public bool canModifyInstance(string uri) {
            net.seabay.polarion.Security.canModifyInstanceRequest inValue = new net.seabay.polarion.Security.canModifyInstanceRequest();
            inValue.uri = uri;
            net.seabay.polarion.Security.canModifyInstanceResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canModifyInstance(inValue);
            return retVal.canModifyInstanceReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canDeleteInstanceResponse net.seabay.polarion.Security.SecurityWebService.canDeleteInstance(net.seabay.polarion.Security.canDeleteInstanceRequest request) {
            return base.Channel.canDeleteInstance(request);
        }
        
        public bool canDeleteInstance(string uri) {
            net.seabay.polarion.Security.canDeleteInstanceRequest inValue = new net.seabay.polarion.Security.canDeleteInstanceRequest();
            inValue.uri = uri;
            net.seabay.polarion.Security.canDeleteInstanceResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canDeleteInstance(inValue);
            return retVal.canDeleteInstanceReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canReadKeyResponse net.seabay.polarion.Security.SecurityWebService.canReadKey(net.seabay.polarion.Security.canReadKeyRequest request) {
            return base.Channel.canReadKey(request);
        }
        
        public bool canReadKey(string uri, string key) {
            net.seabay.polarion.Security.canReadKeyRequest inValue = new net.seabay.polarion.Security.canReadKeyRequest();
            inValue.uri = uri;
            inValue.key = key;
            net.seabay.polarion.Security.canReadKeyResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canReadKey(inValue);
            return retVal.canReadKeyReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canModifyKeyResponse net.seabay.polarion.Security.SecurityWebService.canModifyKey(net.seabay.polarion.Security.canModifyKeyRequest request) {
            return base.Channel.canModifyKey(request);
        }
        
        public bool canModifyKey(string uri, string key) {
            net.seabay.polarion.Security.canModifyKeyRequest inValue = new net.seabay.polarion.Security.canModifyKeyRequest();
            inValue.uri = uri;
            inValue.key = key;
            net.seabay.polarion.Security.canModifyKeyResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canModifyKey(inValue);
            return retVal.canModifyKeyReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canAddElementToKeyResponse net.seabay.polarion.Security.SecurityWebService.canAddElementToKey(net.seabay.polarion.Security.canAddElementToKeyRequest request) {
            return base.Channel.canAddElementToKey(request);
        }
        
        public bool canAddElementToKey(string uri, string key) {
            net.seabay.polarion.Security.canAddElementToKeyRequest inValue = new net.seabay.polarion.Security.canAddElementToKeyRequest();
            inValue.uri = uri;
            inValue.key = key;
            net.seabay.polarion.Security.canAddElementToKeyResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canAddElementToKey(inValue);
            return retVal.canAddElementToKeyReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.canRemoveElementFromKeyResponse net.seabay.polarion.Security.SecurityWebService.canRemoveElementFromKey(net.seabay.polarion.Security.canRemoveElementFromKeyRequest request) {
            return base.Channel.canRemoveElementFromKey(request);
        }
        
        public bool canRemoveElementFromKey(string uri, string key) {
            net.seabay.polarion.Security.canRemoveElementFromKeyRequest inValue = new net.seabay.polarion.Security.canRemoveElementFromKeyRequest();
            inValue.uri = uri;
            inValue.key = key;
            net.seabay.polarion.Security.canRemoveElementFromKeyResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).canRemoveElementFromKey(inValue);
            return retVal.canRemoveElementFromKeyReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.getLocationForURIResponse net.seabay.polarion.Security.SecurityWebService.getLocationForURI(net.seabay.polarion.Security.getLocationForURIRequest request) {
            return base.Channel.getLocationForURI(request);
        }
        
        public string getLocationForURI(string uri) {
            net.seabay.polarion.Security.getLocationForURIRequest inValue = new net.seabay.polarion.Security.getLocationForURIRequest();
            inValue.uri = uri;
            net.seabay.polarion.Security.getLocationForURIResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).getLocationForURI(inValue);
            return retVal.getLocationForURIReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.seabay.polarion.Security.hasCurrentUserPermissionResponse net.seabay.polarion.Security.SecurityWebService.hasCurrentUserPermission(net.seabay.polarion.Security.hasCurrentUserPermissionRequest request) {
            return base.Channel.hasCurrentUserPermission(request);
        }
        
        public bool hasCurrentUserPermission(string permission, string projectId) {
            net.seabay.polarion.Security.hasCurrentUserPermissionRequest inValue = new net.seabay.polarion.Security.hasCurrentUserPermissionRequest();
            inValue.permission = permission;
            inValue.projectId = projectId;
            net.seabay.polarion.Security.hasCurrentUserPermissionResponse retVal = ((net.seabay.polarion.Security.SecurityWebService)(this)).hasCurrentUserPermission(inValue);
            return retVal.hasCurrentUserPermissionReturn;
        }
    }
}
